[project]
name = "67conductor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.0, <3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "mediapipe>=0.10.21",
]
